[build-system]
requires = ["hatchling==1.31.0"]
build-backend = "hatchling.build"

[project]
name = "{{cookiecutter.pypi_package_name}}"
version = "0.1.0"
description = "{{cookiecutter.project_short_description}}"
readme = "README.md"
requires-python = ">= 3.10"

authors = [{name = "{{cookiecutter.org}}", email = "{{cookiecutter.email}}"}]



maintainers = [
  {name = "{{cookiecutter.org}}", email = "{{cookiecutter.email}}"}
]

dependencies = []

[project.optional-dependencies]
dev = [
    "datamodel-code-generator==0.83.0",
    "ruff>=0.16.9",
    "pytest>=9.1.1",
    "ty>=0.0.85",
    "pytest-cov>=7.0.0"
]

docs = [
    "zensical>=0.0.68",
    "mkdocstrings-python==2.0.9",
]

[project.scripts]
{{cookiecutter.pypi_package_name}} = "{{cookiecutter.project_slug}}.__main__:main"



[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # Pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "UP",  # pyupgrade
]

[tool.uv]
package = true
